phelp_dynamics = "Dynamics flavour: 'EI' for excitation/inhibition (C1* backends) or 'SIR' for infection/recovery."
phelp_mu = "Infection rate μ used by the ContactProcess (only for pure Python/C0 runs)."
phelp_gamma = "Coupling γ for EI backends; rescaled internally by the average degree."
phelp_activation = "Activation function passed to the nonlinear EI programs."
phelp_state_type = "Internal state representation: 'binary' (0/1) or 'bipolar' (-1/+1)."
phelp_num_log_samples = "Number of logarithmic sampling points for density/snapshot output modes."
phelp_steps = "Monte Carlo sweeps (each step performs N single updates)."
phelp_simref = "Size-normalised time; steps = simref × N (each step is a full sweep)."
phelp_ic_contact = "Initial condition for the ContactProcess (e.g. 'uniform', 'ground_state')."
phelp_runlang_contact = "Execution backend for the ContactProcess (py, C0=SIR, C1=EI final, C1D=EI density, C1S=EI snapshots)."
phelp_randstr_contact = "Append a random string to the run identifier for unique exports."
phelp_outsuffix_contact = "Optional suffix appended to output/export file names."
phelp_save_frequency = "Save every N averages (0 saves only the final aggregate)."
