"""Simplified implementation of the :class:`MultispectralGraph` subclass.

This version supports exactly two generators:
  - 'multiplicative_cascade' via multiplicative_cascade_graph
  - 'vicsek' via vicsek_graph

All registry dictionaries and unused metadata have been removed.
"""

from __future__ import annotations

from typing import Any, Mapping

import networkx as nx

from ..common import *
from ..SignedGraph.SignedGraph import SignedGraph
from .generators_msg import (
    multiplicative_cascade_graph,
    multiplicative_cascade_probability_matrix,
    multiplicative_cascade_exp_clocks,
    palla_lovasz_vicksek_graph,
    initial_measure,
)


__all__ = ["MultispectralGraph"]

# Mapping for shorter path abbreviations
MSG_TYPE_ABBREV = {
    "multiplicative_cascade": "mc",
    "vicsek": "plv",
}

class MultispectralGraph(SignedGraph):
    """A SignedGraph generated by either 'multiplicative_cascade' or 'vicsek'."""

    def __init__(
        self,
        msg_type: Mapping[str, Any] | str | None = None,
        msg_gen_params: Mapping[str, Any] | None = None,
        stdFnameSFFX: str = MSG_STDFN,
        sgpathn: str = MSG_SGPATH,
        only_const_mode: bool = MSG_ONLY_CONST_MODE,
        **kwargs,
    ) -> None:
        self._verify_pflip(kwargs.get("pflip", 0.0))

        kind, params = self._resolve_kind_and_params(msg_type, msg_gen_params, kwargs)

        self.only_const_mode = only_const_mode
        self.msg_type = kind
        self.std_fname = f"{MSG_PHTABB}{self.msg_type}{stdFnameSFFX}" if stdFnameSFFX else f"{MSG_PHTABB}{self.msg_type}"
        
        # Use abbreviated form for sgpathn
        msg_type_short = MSG_TYPE_ABBREV.get(self.msg_type, self.msg_type)
        self.sgpathn = sgpathn or f"msg_{msg_type_short}"

        if not self.only_const_mode:
            self.G = self._generate(kind, params)
        else:
            self.G = nx.Graph()

        try:
            self.syshapePth = f"{self.msg_type}_N={self.G.number_of_nodes()}"
        except Exception:
            self.syshapePth = self.msg_type

        super().__init__(self.G, **kwargs)

    def _resolve_kind_and_params(
        self,
        msg_type: Mapping[str, Any] | str | None,
        msg_gen_params: Mapping[str, Any] | None,
        overrides: Mapping[str, Any],
    ) -> tuple[str, dict]:
        # Determine kind
        if isinstance(msg_type, str):
            kind = msg_type
        elif isinstance(msg_type, Mapping):
            kind = str(msg_type.get("kind") or msg_type.get("type") or MSG_DEFAULT_TYPE)
        else:
            kind = MSG_DEFAULT_TYPE
        kind = kind.strip().lower()

        # Merge params
        params: dict[str, Any] = {}
        if isinstance(msg_type, Mapping):
            params.update({k: v for k, v in msg_type.items() if k not in {"kind", "type", "params"}})
            params.update(msg_type.get("params", {}) or {})
        if msg_gen_params:
            params.update(dict(msg_gen_params))
        # Also accept overrides from kwargs for common keys
        for key in ("p1", "p2", "p3", "p4", "fraction", "iterations", "stochastic", "N", "pij", "k", "m", "symmetric"):
            if key in overrides:
                params[key] = overrides[key]
        return kind, params

    def _generate(self, kind: str, params: Mapping[str, Any]) -> nx.Graph:
        if kind == "multiplicative_cascade":
            p1 = float(params.get("p1", MSG_P1))
            p2 = float(params.get("p2", MSG_P2))
            p3 = float(params.get("p3", MSG_P3))
            p4 = float(params.get("p4", MSG_P4))
            fraction = float(params.get("fraction", MSG_FRACTION))
            iterations = int(params.get("iterations", MSG_ITERATIONS))
            stochastic = bool(params.get("stochastic", False))
            H = multiplicative_cascade_graph(
                p1, p2, p3, p4,
                fraction=fraction,
                iterations=iterations,
                stochastic=stochastic,
            )
            return nx.convert_node_labels_to_integers(H)

        if kind == "multiplicative_cascade_exp_clocks":
            p1 = float(params.get("p1", MSG_P1))
            p2 = float(params.get("p2", MSG_P2))
            p3 = float(params.get("p3", MSG_P3))
            p4 = float(params.get("p4", MSG_P4))
            fraction = float(params.get("fraction", MSG_FRACTION))
            iterations = int(params.get("iterations", MSG_ITERATIONS))
            stochastic = bool(params.get("stochastic", False))
            A = multiplicative_cascade_probability_matrix(
                p1, p2, p3, p4,
                iterations=iterations,
                stochastic=stochastic,
            )
            H = multiplicative_cascade_exp_clocks(A, fraction)
            return nx.convert_node_labels_to_integers(H)

        if kind == "vicsek":
            N = params.get("N")
            k = params.get("k")
            if N is None or k is None:
                raise ValueError("Vicsek requires 'N' and 'k'.")
            pij = params.get("pij")
            if pij is None:
                m = int(params.get("m", 3))
                symmetric = bool(params.get("symmetric", True))
                pij = initial_measure(m, symmetric=symmetric)
            H, _ = palla_lovasz_vicksek_graph(int(N), pij, int(k))
            return H

        raise ValueError("Unknown msg_type kind. Use 'multiplicative_cascade' or 'vicsek'.")

