DEFAULT_INIT_COND = "uniform"
DEFAULT_RUNLANG = "C1c"
DEFAULT_SIMREF = None
DEFAULT_STEPS = None
DEFAULT_ACTIVATION = "relu"
DEFAULT_STATE_TYPE = "binary"
DEFAULT_NUM_LOG_SAMPLES = 1000
DEFAULT_GAMMA = None
DEFAULT_MU = 1.0
DEFAULT_DYNAMICS = "EI"
DEFAULT_randstr = True
DEFAULT_SAVE_FREQUENCY = 10

# Default sweeps for serializer batch submission
DEFAULT_L2D_CONTACTPROCESS_SRUN_L_LIST = (16, 32, 64)
DEFAULT_L2D_CONTACTPROCESS_SRUN_P_LIST = (0.05, 0.1, 0.2)
DEFAULT_L2D_CONTACTPROCESS_SRUN_GAMMA_LIST = (0.1, 0.2, 0.3)
DEFAULT_L2D_CONTACTPROCESS_SRUN_MU_LIST = (0.5, 1.0, 1.5)
