DEFAULT_INIT_COND = "uniform"
DEFAULT_RUNLANG = "C1c"
DEFAULT_SIM_PREF = 1
DEFAULT_ACTIVATION = "tanh"
DEFAULT_SAVE_DENSITY = False
DEFAULT_STATE_TYPE = "binary"
DEFAULT_NUM_LOG_SAMPLES = 1000
DEFAULT_GAMMA = None
DEFAULT_MU = 1.0
DEFAULT_DYNAMICS = "EI"
DEFAULT_randstr = True

# Serializer defaults
DEFAULT_L2D_CONTACTPROCESS_SRUN_L_LIST = (16, 32, 64)
DEFAULT_L2D_CONTACTPROCESS_SRUN_P_LIST = (0.05, 0.10, 0.20)
DEFAULT_L2D_CONTACTPROCESS_SRUN_GAMMA_LIST = (0.5,)
DEFAULT_L2D_CONTACTPROCESS_SRUN_MU_LIST = (1.0,)
