DEFAULT_BINSC = 500
DEFAULT_EIGMODE = 'scipy'
DEFAULT_EXEC = False
DEFAULT_FREQ = 2
DEFAULT_INSFFX = ''
DEFAULT_mMB = 2**11
DEFAULT_MMB = 2**11
DEFAULT_MORETIME = 0
DEFAULT_NAVG = 500
DEFAULT_NOMAIL = True
DEFAULT_OUTSFFX = ''
DEFAULT_PRINT = False
DEFAULT_PRINT_CHRONO = False
DEFAULT_REMOVE_FILES = True
DEFAULT_SAVING_FREQUENCY = 10
DEFAULT_SHORT = False
DEFAULT_SLANZARV_ID = ""
DEFAULT_VAL = "=1"
DEFAULT_VERBOSE = False
DEFAULT_WORKDIR = ''
## default values depending on default arguments
DEFAULT_DATA_SAVE_FREQ = DEFAULT_NAVG // 10