from numpy import linspace
#
DEFAULT_INIT_COND = 'ground_state_0'
DEFAULT_RUNLANG = 'C1'
DEFAULT_THRMSTEPS = 20
DEFAULT_TEMP_LINSP = linspace(0.1, 2.2, 10).round(decimals=2)
DEFAULT_randstr = True
# Simulated Annealing defaults
DEFAULT_SA_T_INIT = 10.0
DEFAULT_SA_T_FINAL = 0.01
DEFAULT_SA_COOLING_SCHEDULE = 'exponential'
DEFAULT_SA_COOLING_RATE = 0.95
DEFAULT_SA_STEPS_PER_T = 100
DEFAULT_SA_N_TEMPERATURES = 100
# Parallel Tempering defaults
DEFAULT_PT_N_REPLICAS = 8
DEFAULT_PT_T_MIN = 0.5
DEFAULT_PT_T_MAX = 5.0
DEFAULT_PT_T_LADDER_TYPE = 'geometric'
DEFAULT_PT_STEPS_PER_EXCHANGE = 10
DEFAULT_PT_N_EXCHANGES = 1000
