from numpy import linspace
#
DEFAULT_INIT_COND = 'rand'
DEFAULT_RUNLANG = 'C0E'
DEFAULT_THRMSTEPS = 20
DEFAULT_EQSTEP = 20
DEFAULT_TEMP_LINSP = linspace(0.1, 2.2, 10).round(decimals=2)
DEFAULT_randstr = True
# Simulated Annealing defaults
DEFAULT_SA_T_INIT = 10.0
DEFAULT_SA_T_FINAL = 0.01
DEFAULT_SA_COOLING_SCHEDULE = 'exponential'
DEFAULT_SA_COOLING_RATE = 0.95
DEFAULT_SA_STEPS_PER_T = 100
DEFAULT_SA_N_TEMPERATURES = 100
# Parallel Tempering defaults
DEFAULT_PT_N_REPLICAS = 8
DEFAULT_PT_T_MIN = 0.5
DEFAULT_PT_T_MAX = 5.0
DEFAULT_PT_T_LADDER_TYPE = 'geometric'
DEFAULT_PT_STEPS_PER_EXCHANGE = 10
DEFAULT_PT_N_EXCHANGES = 1000
# Topological algorithm defaults
DEFAULT_TOPO_N_MODES = 40
DEFAULT_TOPO_SIGMA_INIT = 0.15
DEFAULT_TOPO_CHUNK_SIZE = 5000
DEFAULT_TOPO_POLISH = True
DEFAULT_TOPO_POLISH_SWEEPS = 50
DEFAULT_TOPO_TAU = 1.0
DEFAULT_TOPO_FIELD_STRENGTH = 1.0
# Cross-Entropy Method (CEM) spectral optimizer defaults
DEFAULT_CEM_ITER = 30
DEFAULT_CEM_POP_SIZE = 128
DEFAULT_CEM_ELITE_FRAC = 0.2
DEFAULT_CEM_INIT_SIGMA = 1.2
DEFAULT_CEM_SMOOTHING = 0.6
DEFAULT_CEM_SIGMA_FLOOR = 1e-3
DEFAULT_CEM_SIGMA_CEILING = 5.0
DEFAULT_CEM_RESTARTS = 10
DEFAULT_CEM_GREEDY = True
DEFAULT_CEM_GREEDY_SWEEPS = 120
# Thermal averaging default
DEFAULT_N_THERMAL = 1
# Quench-id sentinel: -1 disables single-task mode and uses the internal loop.
DEFAULT_QUENCH_ID = -1
# Array-dispatch defaults (used by the serializer only, not the main program)
DISPATCH_CHOICES = ('slanzarv', 'array')
DEFAULT_DISPATCH = 'slanzarv'
DEFAULT_ARRAY_CONCURRENT = 1000
DEFAULT_ARRAY_PARTITION = ''
DEFAULT_ARRAY_TIME = ''
# Result persistence
DEFAULT_SAVE_RESULTS = False
DEFAULT_SAVE_FREQUENCY = 0
DEFAULT_SAVE_ENE = True
DEFAULT_SAVE_MAGN = True
DEFAULT_SAVE_SOUT = False
DEFAULT_SAVE_ALL = False
