DEFAULT_SCS_NN_J = 1.0
DEFAULT_SCS_NN_G = 1.0
DEFAULT_SCS_NN_GAMMA = 1.0
DEFAULT_SCS_NN_DIAGONAL = "-1.0"
DEFAULT_SCS_NN_WORKDIR = "scs_nn"
DEFAULT_SCS_NN_J0 = 0.0
DEFAULT_SCS_NN_BACKEND = "cupy"
DEFAULT_SCS_NN_FLOAT_TYPE = "float64"
DEFAULT_SCS_NN_PARTITION_RULE = ">0"
DEFAULT_SCS_NN_SAVE_FREQUENCY = 0
DEFAULT_SCS_NN_OUT_SUFFIX = ""
DEFAULT_SCS_NN_MODE = "ordParam"
DEFAULT_SCS_NN_NAVG = 1

# Default lists for serialiser batch submission
DEFAULT_SCS_NN_SRUN_N_LIST = (500,)
DEFAULT_SCS_NN_SRUN_GAMMA_LIST = (1.0,)
DEFAULT_SCS_NN_SRUN_J0_LIST = (0.0,)
DEFAULT_SCS_NN_SRUN_J_LIST = (1.0,)
DEFAULT_SCS_NN_SRUN_G_LIST = (1.0,)
DEFAULT_SCS_NN_SRUN_DIAGONAL_LIST = ("-1.0",)
