#
DEFAULT_L2D_TRANSCLUSTER_MODE = 'ordParam'
DEFAULT_L2D_TRANSCLUSTER_FLOAT_TYPE = 'float64'
DEFAULT_L2D_TRANSCLUSTER_SAVE_FREQUENCY = 0
DEFAULT_L2D_TRANSCLUSTER_OUT_SUFFIX = ''
DEFAULT_L2D_TRANSCLUSTER_NAVG = 1000
# Default lists for serialiser batch submission L2D
DEFAULT_L2D_TRANSCLUSTER_SRUN_L_LIST = (10, 20, 30, 40)
DEFAULT_L2D_TRANSCLUSTER_SRUN_P_LIST = (0.1, 0.15, 0.2, 0.25)
DEFAULT_L2D_TRANSCLUSTER_SRUN_MU_LIST = None
DEFAULT_L2D_TRANSCLUSTER_SRUN_SIGMA_LIST = None
DEFAULT_L3D_TRANSCLUSTER_MODE = 'ordParam'
DEFAULT_L3D_TRANSCLUSTER_FLOAT_TYPE = 'float64'
DEFAULT_L3D_TRANSCLUSTER_SAVE_FREQUENCY = 0
DEFAULT_L3D_TRANSCLUSTER_OUT_SUFFIX = ''
DEFAULT_L3D_TRANSCLUSTER_NAVG = 1000
DEFAULT_L3D_TRANSCLUSTER_PDIL = 0.0
DEFAULT_L3D_TRANSCLUSTER_MU = 0.0
DEFAULT_L3D_TRANSCLUSTER_SIGMA = 0.0
DEFAULT_L3D_TRANSCLUSTER_EDGE_WEIGHT = 'flip'
# Default lists for serialiser batch submission L3D
DEFAULT_L3D_TRANSCLUSTER_SRUN_L_LIST = (10, 20, 30, 40)
DEFAULT_L3D_TRANSCLUSTER_SRUN_P_LIST = (0.1, 0.15, 0.2, 0.25)
DEFAULT_L3D_TRANSCLUSTER_SRUN_MU_LIST = None
DEFAULT_L3D_TRANSCLUSTER_SRUN_SIGMA_LIST = None
# Default lists for serialiser batch submission SCS
DEFAULT_SCS_TRANSCLUSTER_SRUN_N_LIST = (8, 10, 12, 14)
DEFAULT_SCS_TRANSCLUSTER_SRUN_GAMMA_LIST = (0.1, 0.2, 0.3, 0.4)
DEFAULT_SCS_TRANSCLUSTER_SRUN_J0_LIST = (0.0, 0.5, 1.0)
DEFAULT_SCS_TRANSCLUSTER_SRUN_J_LIST = (1.0, 2.0, 3.0)
DEFAULT_SCS_TRANSCLUSTER_SRUN_G_LIST = (0.0, 0.1, 0.2)
