DEFAULT_L2D_TRANSCLUSTER_MODE = 'ordParam'
DEFAULT_L2D_TRANSCLUSTER_FLOAT_TYPE = 'float64'
DEFAULT_L2D_TRANSCLUSTER_SAVE_FREQUENCY = 0
DEFAULT_L2D_TRANSCLUSTER_OUT_SUFFIX = ''
DEFAULT_L2D_TRANSCLUSTER_PREW = 0.0
DEFAULT_L2D_TRANSCLUSTER_NAVG = 1000
